import React from 'react'
import Head from 'next/head'

const Home: React.FC = () => {
   return (
      <div>
         <Head>
            <title>Pokedash</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main>
            <h1>Welcome to Pokedash!</h1>
         </main>
      </div>
   )
}

export default Home
